name: Fedora
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  test:
    name: fedora
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora:39
      - name: Get source
        uses: actions/checkout@v3
        with:
          path: 'red_amber'
      - name: Create container and run tests
        run: |
          {
              echo 'FROM fedora:39'
              echo 'RUN dnf -y update'
              echo 'RUN dnf -y install gcc-c++ git libarrow-devel libarrow-glib-devel ruby-devel'
              echo 'RUN dnf clean all'
              echo 'COPY red_amber red_amber'
              echo 'WORKDIR /red_amber'
              echo 'RUN bundle install'
          } > podmanfile
          echo 'RUN bundle exec rake test' >> podmanfile
          podman build --tag fedora38test -f ./podmanfile
